version: '2'
services:
  youtrack:
    image: jetbrains/youtrack
    container_name: youtrack
    ports:
      - 8080:8080
    restart: always
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    ports:
      - 8080:8080
  mattermost:
    image: mattermost/mattermost-team-edition
    container_name: mattermost
    ports:
      - 8080:8080
  seafile:
    image: jenserat/seafile
    container_name: seafile
    ports:
      - 10001:10001
      - 12001:12001
      - 8000:8000
      - 8080:8080
      - 8082:8082
  paperless:
    image: danielquinn/paperless
    container_name: paperless
    ports:
      - 8000:8000

